### ISSUE TITLE
docker failed opendsa-lti_1 exited with code 1

### ISSUE THREAD

**Issue by znAaron** [OpenDSA/OpenDSA-DevStack#11]
Initially, I can not start the docker, it gives an error "build path OpenDSA-LTI either does not exist, is not accessible, or is not a valid URL." So I clone the LTI repository to the dev-stack folder and used "make up". But I could not get the server running, the is no message thin server message, instead, it says opendsa-lti_1 exited with code 1. It will always automatically exit when I try to start the opendsa-lti_1 server.

**Comment by znAaron** [comment]
It is a problem with the windows ending of a line being different from the Unix system. I would suggest adding additional documents in the instruction.

**Comment by weihao** [comment]
Resolved in https://github.com/OpenDSA/OpenDSA-DevStack/commit/cf93373d74c0308d30d899163f239361fab7a9cb
