### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by sublime09** [OpenDSA/OpenDSA-DevStack#3]
### ~~Progress will be on this repo's [Python 3 branch](https://github.com/OpenDSA/OpenDSA-DevStack/tree/python3.8)~~
> UPDATE 27/6/2020: Python 3 branch has been merged into the master branch! 

### Sister issue to [OpenDSA's Python3 issue](https://github.com/OpenDSA/OpenDSA/issues/162)

The Dev-Stack of OpenDSA should also be targeting python 3.

**Comment by sublime09** [comment]
The DevStack is working well with the python3 branch of OpenDSA as of now, creating and using a python virtual environment.  Additionally, NodeJS update from 8 to 12 seems to not bring up any new issues as well.  Although the LTI and the codeworkout repositories are untested on these changes.  

Note that `vagrant up` should be run as from an admin command prompt, PowerShell, root, etc.   Otherwise the python virtual environment will produce a `Protocol Error: 71`.  

Also note that `pip install` usually errors without root access.  And `sudo pip install` will error because the .pyVenv is not activated for single commands though sudo.  The simple way around this is to `sudo bash` to have a dedicated root shell, then have the .pyVenv activated, and finally do any `pip install` that you need.

**Comment by weihao** [comment]
After `vagrant up`, I am having issues connecting to the local MySQL server.
```
vagrant@ubuntu-bionic:/vagrant$ Could not find rake-11.2.2 in any of the sources
Run `bundle install` to install missing gems.
Thin web server (v1.7.2 codename Bachmanity)
Maximum connections set to 1024
Listening on 0.0.0.0:9292, CTRL+C to stop
[Worker(host:ubuntu-bionic pid:1997)] Starting job worker
[Worker(host:ubuntu-bionic pid:1997)] Error while reserving job: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory")
[Worker(host:ubuntu-bionic pid:1997)] Error while reserving job: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory")
```

using branch `* python3.8`

**Comment by Raghu1320** [comment]
After running 'bundle install' in the OpenDSA-LTI repository, I am getting the following error: 
![Screen Shot 2020-04-28 at 3 59 27 PM](https://user-images.githubusercontent.com/25236056/80531861-4460fe00-8969-11ea-9f3a-540512126514.png)
on the python3.8 branch.

**Comment by cashaffer** [comment]
Is there something that still needs to be resolved?

**Comment by sublime09** [comment]
Sorry for the delay, @Raghu1320 .   I see in your output 'gems/2.3.0'.  Could that version of ruby/gems be unsupported on the new DevStack VM (bionic; Ubuntu 18)?  For both the python3 and master branches, the bootstrap.sh file of Dev-Stack explicitly tries to install ruby version 2.3 (which gives gems too).  Maybe we should move ahead and try upgrading ruby/gems to see if that works on the VM?  

Searching around, I came across [this](https://github.com/eventmachine/eventmachine/issues/853) which seems to be a similar error.  They say it is caused by a mismatch between gcc48 and gcc72 on machines (needing one, but instead using the other).  `apt-get install ruby-dev` is their fix.  I notice they don't specify a version, so apt finds the default supported one for their machine.  

So now I had a feeling that upgrading ruby/gems would solve this.  I went ahead and tried this kind of setup:

```
sudo apt install ruby
sudo apt install ruby-dev
# These ^ seem to automatically install ruby 2.5 on our new VM (bionic). 
# In the future, we may want to declare a version explicitly.   
# After this: ruby --version is '2.5.7' and gem --version is '2.7.6.2' 

sudo gem install rake --version 11.2.2
# I saw this was added to Dev-Stack's master branch, so I'll follow too.  
# Might not be necessary though.  

sudo gem install bundler --version 1.17.3
# Here's the same bundler that the master branch has been using for awhile now

cd /vagrant/OpenDSA-LTI
bundle install
```

And now I see `Bundle complete! 98 Gemfile dependencies, 200 gems now installed.`   No fatal errors, so this looks to be a possible solution!  However, I haven't gone any farther in testing OpenDSA-LTI, so it's not a proven solution.  

If we can't try out ruby/gems 2.5, then I need to see exactly what your VM is using.  Then I'll be able to mimic your setup and see if the error is reproduceable.  Can you show me the output of this on your machine: `gem list | grep "bundler\|rake\|eventmachine\|thin"` .  Showing me `ruby --version` and `gem --version` would also be good, thanks.

Question: are you using OpenDSA's python3 branch within the OpenDSA repo?  Dev-Stack's bootstrap.sh script will just grab the master branch of OpenDSA if the OpenDSA directory is missing.  Right now, I am using the Dev-Stack's python3.8 branch AND OpenDSA's python3 branch at the same time.

Let me know if this works!  I am looking into @weihao 's error now.

**Comment by sublime09** [comment]
@weihao, I could really use more info about the issue you are running into.  I can't tell from your post what the **exact command** you are entering to get that error.  Was it simply the `mysql` command to enter the mysql console, executing a script, or something more complicated?  Are you sure the initial partitioning (the bootstrap.sh file) of OpenDSA-DevStack showed no issues?  Was there any setup you did after doing `vagrant up` on the machine for the first time?   Sorry about all the questions, but this really helps me know what is happening on your end.  

You seem worried about the mysql connection, but your error suggests that rake and bundler is the _first_ issue that occurs.  So lets clear that up first.  The error message sounds like rake isn't being installed by running `bundle install` .  Can you tell me what the output of `gem list --local | grep "rake\|bundler"` is?

Looking around, I also notice that there is a "Ubuntu18Install.md" file in the OpenDSA-LTI repository, with some _very slightly_ modified instructions for deploying OpenDSA-LTI server.  Since the python3.8 branch of OpenDSA-DevStack is an Ubuntu18 VM, could that help you?  Or maybe you are already using it.  It's actually newer than the main README.md file of OpenDSA-LTI, and shows some different packages (though most are already installed from OpenDSA-DevStack).  I compared the packages they say to install, and here are the differences:

|     **Ubuntu18Install.md**     |          **README.md**         |
|:--------------------------:|:--------------------------:|
| autoconf                   | build-essential            |
| bison                      | git-core                   |
| gcc                        | libcurl4-openssl-dev       |
| libcurl4-gnutls-dev        | libmariadbclient-dev       |
| libmariadb-client-lgpl-dev | libsqlite3-dev             |
| libssl1.0-dev              | libssl-dev                 |
| make | libxml2-dev                |
| software-properties-common                   | libxslt-dev                |
|  stunnel4                          | libyaml-dev                |
|                            | python-software-properties |
|                            | sqlite3                    |
|                            | zlib1g-dev                 |

I didn't know that sqlite3 was being used on OpenDSA-LTI.  Or maybe those can be removed?

**Comment by sublime09** [comment]
I did a bit more digging into the issue @weihao came across.  I think it was an error in the bootstrap.sh file used during `vagrant up` which then skips over the entire section that installs and sets up mysql.  I just made a push to the python3.8 branch (948c167da7a248ecd5e760bc98fe805b816d8497) which would solve that issue.  Can you check and see if that is resolved for you too?

**Comment by znAaron** [comment]
Unable to get the ruby on rails server running. While running the server, the terminal says 'Could not find rake-11.2.2 in any of the sources'. Also, https://192.168.33.10:9292/ shows an error says ''ActiveRecord::PendingMigrationError"

**Comment by sublime09** [comment]
@znAaron , I've sent you and email connecting you with someone who is more familiar with the Ruby upgrades and OpenDSA-LTI.  I've been more focused on the python3 side of things, so sorry if my changes have broken the Ruby install or Rails server!  Hopefully they can weigh in here or reply by email and give you some more direction.  

The error message after requesting that URL sounds like it is a ruby or rails issue.  But just as a precaution, double check your [Vagrantfile](https://github.com/OpenDSA/OpenDSA-DevStack/blob/python3.8/Vagrantfile) file's forwarded ports of the VM.  I've uncommented some of the those lines on my local workspace for instance.

**Comment by sublime09** [comment]
I have now merged the python3 branch into the master branch: 5b5c8b77e24fa1bc1b23c0fc1907c85a424c3661

I hope everyone is happy with the changes!  If so, I will close this issue soon
